=== maxburian/SAXS_py3/SAXS/schema.json
{
	"type": "object",
	"$schema": "http://json-schema.org/draft-03/schema",
	"required": true,
	"description": "The SAXS configuration file specifies the parameters of a SAXS sensor calibration. It is written in the JSON format which governs the general syntax.",
	"additionalProperties": false,
	"properties": 
	{
		"Title": 
		{
			"type": "string"
		},

		"Geometry": 
		{
			"type": "object",
			"required": true,
			"properties": 
			{
				"Tilt": 
				{
					"description": "The sensor, usually is not perfectly perpenticular to the ray direction. The tilt angle can be specified by giving the following paramters.",
					"type": "object",
					"required": true,
					"additionalProperties": false,
					"properties": 
					{
						"TiltRotDeg": 
						{
							"description": "This gives the angel of the tilt direction.",
							"type": "number",
							"units": "degree",
							"default": 0,
							"required": true
						},

						"TiltAngleDeg": 
						{
							"description": "This gives the angle between the ray direction and the normal to the sensor plane.",
							"units": "degree",
							"type": "number",
							"default": 0,
							"required": true
						}
					}
				},

				"BeamCenter": 
				{
					"description": "Gives the beam center in pixel coorinates.",
					"type": "array",
					"minItems": 2,
					"maxItems": 2,
					"required": true,
					"units": "Pixel",
					"default": 
					[
						900.00,
						300.00
					],

					"items": 
					{
						"type": "number",
						"required": true,
						"labels": 
						[
							"y",
							"x"
						]
					}
				},

				"DedectorDistanceMM": 
				{
					"description": "Distance between diffraction center and sensor.",
					"type": "number",
					"units": "Millimeters",
					"default": 1000.00,
					"required": true
				},

				"PixelSizeMicroM": 
				{
					"description": "The pixel size on the sensor.",
					"units": "Microns",
					"type": "array",
					"minItems": 1,
					"maxItems": 2,
					"required": true,
					"default": 
					[
						172.0
					],

					"items": 
					{
						"type": "number",
						"units": "Microns",
						"required": true,
						"default": 172.0,
						"labels": 
						[
							"y and x",
							"x"
						]
					}
				},

				"Imagesize": 
				{
					"description": "Size of sensor image in pixel.",
					"type": "array",
					"minItems": 2,
					"maxItems": 2,
					"units": "Pixel",
					"required": true,
					"default": 
					[
						1043,
						981
					],

					"items": 
					{
						"type": "integer",
						"units": "Pixels",
						"required": true,
						"labels": 
						[
							"y",
							"x"
						]
					}
				}
			}
		},
		
        "Wavelength": 
        {
            "description": "Refined wavelength.",
            "units": "Angstrom",
            "type": "number",
            "required": true,
            "default": 1.54000
        },
        
		"Masks": 
		{
			"type": "array",
			"minItems": 1,
			"required": true,
			"items": 
			{
				"type": "object",
				"properties": 
				{
					"MaskFile": 
					{
						"description": "Path of Maskfile",
						"type": "string",
						"default": "AAA_integ.msk",
						"required": true,
						"appinfo": 
						{
							"editor": "File",
							"display": "MaskFile"
						}
					},

					"Oversampling": 
					{
						"description": "Oversampling factor for radial integration. The higher, the longer the setup but the higher the accuracy. More then 3 is probably overkill. ",
						"type": "integer",
						"default": 3,
						"required": true
					},

					"PixelPerRadialElement": 
					{
						"description": "Expresses the width of a radial step in terms of pixels. '1' means :math:`\\delta R\\approx 1` :ref:`PixelSizeMicroM`.",
						"required": true,
						"type": "number",
						"default": 1,
						"units": "Pixel"
					},

					"Name": 
					{
						"description": "Name for mask configuration.",
						"type": "string"
					},
					
					        
                    "Phi-mode": 
                    {
                        "description": "Perform integration over q_min to q_max and obtain I(phi) ",
                        "type": "boolean",
                        "required": false,
                        "default": false
                    },
					
					"qStart":
					{
					   "description": "Starting q-value for integral parameters or phi integration.",
					   "type": "number",
					   "default": 0,
					   "required": true,
					   "units" : "nm^-1"
					},
					
					"qStop":
                    {
                       "description": "Ending q-value for integral parameters or phi integration.",
                       "type": "number",
                       "default": 0,
                       "required": true,
                       "units" : "nm^-1"
                    }
				}
			}
		},
        
		"Slices": 
		{
			"type": "array",
			"description": "Slices are designed to analyse GISAXS data.It allows you to specify slices along the sensor axis and get intensity along :math:`q_x`, :math:`q_z` directions.",
			"items": 
			{
				"type": "object",
				"properties": 
				{
					"Direction": 
					{
						"type": "string",
						"required": true,
						"default": "x",
						"enum": 
						[
							"x",
							"y"
						],

						"description": "'x' or 'y' direction in sensor pixel coordinates."
					},

					"Plane": 
					{
						"type": "string",
						"required": true,
						"default": "InPlane",
						"enum": 
						[
							"InPlane",
							"Vertical"
						],

						"description": "Whether the direction is in plane with scattering surface or vertical to it."
					},

					"CutPosition": 
					{
						"type": "integer",
						"required": true,
						"default": "0",
						"units": "Pixel",
						"description": "Cut position in pixel coordinates in the other coodinate then specified in 'Direction'. Origin is top left Corner."
					},

					"CutMargin": 
					{
						"type": "integer",
						"required": true,
						"default": 1,
						"units": "Pixel",
						"description": "Number of pixels left and right from  cut to include into the average ."
					},

					"IncidentAngle": 
					{
						"type": "number",
						"required": true,
						"units": "degree",
						"default": 0,
						"description": "Angle of incidence in GISAXS setup."
					},

					"MaskRef": 
					{
						"required": true,
						"type": "integer",
						"default": 0,
						"description": "Chose which mask to use for the sclice. '-1' means don't use mask"
					}
				}
			}
		},
		
        "GISAXSmode": 
        {
            "description": "Run integration in GI-SAXS mode (no radial integration - only slcies?).",
            "type": "boolean",
            "required": false,
            "default": false
        },
        
		"PolarizationCorrection": 
		{
			"description": "The scattering direction id dependend on the light polarization. This may be acconted for with the polarization correction.",
			"required": false,
			"type": "object",
			"default": 
			{
				"Fraction": 0.95,
				"Angle": 0
			},

			"minItems": 1,
			"additionalProperties": false,
			"properties": 
			{
				"Fraction": 
				{
					"description": "Fraction of light polarized in the given (:ref:`Angle`) direction.",
					"required": true,
					"type": "number",
					"default": 0.95
				},

				"Angle": 
				{
					"description": "Angle of the polarization plane.",
					"required": true,
					"type": "number",
					"default": 0.0,
					"units": "degree"
				}
			}
		},

		"Directory": 
		{
			"type": "array",
			"required": true,
			"minItems": 1,
			"description": "Directory to take into acount for processing images. Given as a list of subdirectories.",
			"items": 
			{
				"type": "string",
				"default": ".",
				"appinfo": 
				{
					"editor": "RemoteDir"
				}
			}
		},
		
		"Live-Filelisting": 
        {
            "description": "Automatically writes integrated filenames with path into /./results/filelist_setup.txt ",
            "type": "boolean",
            "required": false,
            "default": true
        },
        
        "OverwriteFiles":
        {
            "description": "Overwrite existing *.chi files during integration (True) or integrate only missing files?",
            "type": "boolean",
            "required": false,
            "default": true
        },

		"Threads": 
		{
			"default": 2,
			"type": "integer"
		}
	}
}

=== maxburian/SAXS_py3/doc/calgeo.json
{
    "Title": "Example Calibration",
    "Geometry": {
        "Tilt": {
            "TiltAngleDeg": -10,
            "TiltRotDeg": 73.569
        },
        "DedectorDistanceMM": 1031.657,
        "BeamCenter": [
            808.37,
            387.772
        ],
        "Imagesize": [
            1043,
            981
        ],
        "PixelSizeMicroM": [
            172.0,
            172.0
        ]
    },
    "Directory": [
        "."
    ],
    "Masks": [
        {
            "PixelPerRadialElement": 1,
            "MaskFile": "emptymask.tif",
            "Oversampling": 2,
            "Name": "",
            "Phi-mode": false,
            "qStart": 0.0, 
            "qStop": 5.0
        }],
    "Slices": [],
    "GISAXSmode": false,
    "Wavelength": 1.54,
    "Live-Filelisting": true,
    "OverwriteFiles": true,
    "Threads": 2
}
